comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
codecov:
  token: f006cd2e-adbc-457c-b4cf-d80b8b6f616c
