// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// tsmvr_solve
List tsmvr_solve(const arma::mat& X, const arma::mat& Y, const int& s1, const int& s2, const std::string& B_type, const std::string& Omega_type, const double& eta1, const double& eta2, const double& epsilon, const int& max_iter, const int& skip, const bool& quiet, const bool& suppress_warnings);
RcppExport SEXP _tsmvr_tsmvr_solve(SEXP XSEXP, SEXP YSEXP, SEXP s1SEXP, SEXP s2SEXP, SEXP B_typeSEXP, SEXP Omega_typeSEXP, SEXP eta1SEXP, SEXP eta2SEXP, SEXP epsilonSEXP, SEXP max_iterSEXP, SEXP skipSEXP, SEXP quietSEXP, SEXP suppress_warningsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const int& >::type s1(s1SEXP);
    Rcpp::traits::input_parameter< const int& >::type s2(s2SEXP);
    Rcpp::traits::input_parameter< const std::string& >::type B_type(B_typeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type Omega_type(Omega_typeSEXP);
    Rcpp::traits::input_parameter< const double& >::type eta1(eta1SEXP);
    Rcpp::traits::input_parameter< const double& >::type eta2(eta2SEXP);
    Rcpp::traits::input_parameter< const double& >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< const int& >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const int& >::type skip(skipSEXP);
    Rcpp::traits::input_parameter< const bool& >::type quiet(quietSEXP);
    Rcpp::traits::input_parameter< const bool& >::type suppress_warnings(suppress_warningsSEXP);
    rcpp_result_gen = Rcpp::wrap(tsmvr_solve(X, Y, s1, s2, B_type, Omega_type, eta1, eta2, epsilon, max_iter, skip, quiet, suppress_warnings));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_tsmvr_tsmvr_solve", (DL_FUNC) &_tsmvr_tsmvr_solve, 13},
    {"run_testthat_tests", (DL_FUNC) &run_testthat_tests,  0},
    {NULL, NULL, 0}
};

RcppExport void R_init_tsmvr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
