/*

#include <RcppArmadillo.h>
// [[Rcpp::depends(RcppArmadillo)]]

using namespace Rcpp;
using namespace arma;

// This is start of the header guard.  ADD_H can be any unique name.  By convention, we use the name of the header file.
#ifndef TSMVR_H
#define TSMVR_H

// This is the content of the .h file, which is where the declarations go
arma::mat ppmat(const arma::mat &X);

// This is the end of the header guard
#endif

 */
